//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygunitem
{
    using System;
    using System.Collections.Generic;
    
    public partial class cekilen_datalar
    {
        public int cekilen_data_id { get; set; }
        public string cekilen_isim { get; set; }
        public double cekilen_fiyat { get; set; }
        public string cekilen_firma { get; set; }
        public System.DateTime cekilen_tarih { get; set; }
        public string cekilen_logo { get; set; }
        public string cekilen_url { get; set; }
        public int cekilen_durum { get; set; }
    }
}
