//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygunitem
{
    using System;
    using System.Collections.Generic;
    
    public partial class hataliUrunler
    {
        public int hataliUrun_autoincr { get; set; }
        public int hataliUrun_id { get; set; }
        public string hataliUrun_firma { get; set; }
        public string hataliUrun_link { get; set; }
        public int hataliUrun_dbSatir { get; set; }
        public string hataliUrun_adi { get; set; }
    }
}
