//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygunitem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uygunitemdb : DbContext
    {
        public uygunitemdb()
            : base("name=uygunitemdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminListesi> adminListesi { get; set; }
        public virtual DbSet<alt_kategoriler> alt_kategoriler { get; set; }
        public virtual DbSet<cekilen_datalar> cekilen_datalar { get; set; }
        public virtual DbSet<data_siteler> data_siteler { get; set; }
        public virtual DbSet<footer> footer { get; set; }
        public virtual DbSet<hakkimizda> hakkimizda { get; set; }
        public virtual DbSet<hataliUrunler> hataliUrunler { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<menuKategoriler> menuKategoriler { get; set; }
        public virtual DbSet<mesaj> mesaj { get; set; }
        public virtual DbSet<sponsorlar> sponsorlar { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<uruntakip> uruntakip { get; set; }
        public virtual DbSet<yorumlar> yorumlar { get; set; }
    }
}
