//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygunitem
{
    using System;
    using System.Collections.Generic;
    
    public partial class sponsorlar
    {
        public int sponsor_autoincr { get; set; }
        public string sponsor_firmalink { get; set; }
        public int sponsorluk_gunsuresi { get; set; }
        public Nullable<System.DateTime> sponsorluk_baslangic { get; set; }
    }
}
