//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygunitem
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorumlar
    {
        public int yorum_id { get; set; }
        public int urun_id { get; set; }
        public string yorum { get; set; }
        public System.DateTime tarih { get; set; }
        public string mail { get; set; }
        public string isim { get; set; }
        public string urun_isim { get; set; }
        public int yorumDurum { get; set; }
    }
}
