//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygunitem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesaj
    {
        public int mesaj_id { get; set; }
        public string ad { get; set; }
        public string email { get; set; }
        public string konu { get; set; }
        public string mesaj1 { get; set; }
    }
}
