//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygunitem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uruntakip
    {
        public int id { get; set; }
        public string kullanici_mail { get; set; }
        public string takip_urun { get; set; }
        public double takip_sonfiyat { get; set; }
        public System.DateTime takip_tarih { get; set; }
    }
}
